language: objective-c
osx_image: xcode7.3
script: 
  - xctool -project BlueChatLib/BlueChatLib.xcodeproj -scheme BlueChatLib -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPad Air 2,OS=9.3" build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
